build:
  image: matjazp/hugo-ci
  commands:
    - hugo
    - mv -f public /tmp/public
    - rm -rf .
    - mv -f /tmp/public .
deploy:
  git_push:
    branch: master
    remote: git@github.com:garazaFRI/garazafri.github.io.git
    force: true
    commit: true
    when:
        branch: master