build:
  image: matjazp/hugo-ci
  commands:
    - hugo
    - mv -f public /tmp/public
    - find -delete
    - shopt -s dotglob
    - mv -f /tmp/public/* .
    - ls -la
    - git init
    - git config user.email "drone@garaza.io"
    - git config user.name "drone-ci"
    - git add --all
    - git commit -m "deploy from drone-ci"
deploy:
  git_push:
    branch: master
    remote: git@github.com:garazaFRI/garazafri.github.io.git
    force: true
    commit: true
    when:
        branch: master