baseurl = "http://garaza.io/"
languageCode = "en-us"
title = "Garaža FRI | Študentski tehnološki pospeševalnik"
theme = "garaza"
author = "Blaz Kostanjsek"
canonifyurls = true
paginate = 10

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Želiš uresničiti svoje ideje? Postani del Garaže."
  googleAnalytics = "UA-78366821-1"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "O Garaži"
    weight = 0
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Programi"
    weight = 1
    identifier = "program"
    url = "/program/"
  [[menu.main]]
    name = "Dogodki"
    weight = 2
    identifier = "event"
    url = "/event/"
  [[menu.main]]
    name = "Ekipe"
    weight = 3
    url = "/teams/"
  [[menu.main]]
    name = "Pridruži Se"
    weight = 4
    url = "/join/"
  [[menu.main]]
    name = "FAQ"
    weight = 5
    url = "/faq/"



[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "garazaFRI"
  facebook = "*"
  instagram = "garazafri"
  github = "garazaFRI"
  # stackoverflow = "*"
  # linkedin = "*"
